parameters:
  name: 'DotNetCore_Framework_Job'
  buildConfiguration: 'Release'
  pool: Default
  CASCADES: ''

jobs:
- job: 'DotNetCore_Build'
  pool: ${{ parameters.pool }}
  variables:
  - group: global-var-pipelines

  steps:
  - checkout: self
    submodules: recursive

  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.2.203'

  - task: DotNetCoreCLI@2
    displayName: Restore from nuget
    inputs:
      command: 'restore'
      arguments: '--no-build'
      feedsToUse: 'select'
      versioningScheme: 'off'
      nuGetFeedType: 'internal'
      nugetConfigPath: $(Build.ArtifactStagingDirectory)

  - task: DotNetCoreCLI@2
    displayName: Build release
    inputs:
      command: build
      projects: 'Source/**/*.csproj'
      arguments: '--configuration ${{ parameters.buildConfiguration }} --no-restore' # Update this to match your need
      packagesDirectory: $(Build.ArtifactStagingDirectory)
  
  - task: DotNetCoreCLI@2
    displayName: Run Tests
    inputs:
      command: test
      projects: 'Specifications/**/*.csproj'
      arguments: '--configuration ${{ parameters.buildConfiguration }}'
  
  - template: ../Versioning/set_version_variable.yml
      
  - task: DotNetCoreCLI@2
    displayName: Packing
    inputs:
      projects: 'Source/**/*.csproj'
      command: 'pack'
      versioningScheme: byEnvVar
      versionEnvVar: NEW_VERSION
      outputDir: '$(Build.ArtifactStagingDirectory)'

  - template: cascades.yml
    parameters:
      CASCADES: ${{ parameters.CASCADES }}

- job: 'Release'
  pool: Default
  dependsOn: 'DotNetCore_Build'
  condition: succeeded()
  variables:
  - group: global-var-pipelines
  - name: NEW_VERSION
    value: $[ dependencies.DotNetCore_Build.outputs['set_version.Version'] ]

  steps:
  - template: ../Versioning/commit_version_tag.yml
  
  - download: current
    artifact: 'NugetPack'
  
  - script: ls -R  $(Pipeline.Workspace)
    displayName: Checking packages
  
  - task: NuGetCommand@2
    displayName: Push Nuget packs
    condition: ne( variables.NEW_VERSION , 'empty')
    inputs:
      command: push
      nugetFeedType: 'external'
      packagesToPush: ' $(Pipeline.Workspace)/**/*.nupkg'
      publishFeedCredentials: 'myget_mathieu'


- job: 'Documentation'
  pool: Default
  dependsOn: DotNetCore_Build
  condition: succeeded()
  variables:
  - group: global-var-pipelines
  steps:
  - template: ../Documentation/documentation.yml
   
   
# echo PullRequest  49e27cc18f57870206171925a8c540abdac7bbfb 2.0.0
# echo IndividualCI 036100265b6d83d536827451131bf8c306ce9d43 2.0.0
