parameters:
  name: 'Versioning'
  buildConfiguration: 'Release'
  pool: Default
  CASCADES: ''
## To get the versioning label, please use this in the .yml calling this one and pass it in parameters
##    URL=$(Build.Repository.Uri)
##    REPO=`echo "$URL" | awk -F ".com/" '{ print $2 }'`
##    LABEL=`GET https://api.github.com/repos/$REPO/pulls\?state\=all | tr ',' '\n' | grep labels | head -1 | cut -d ":" -f 2 | tr -d '[' | tr -d ']'`
  LABEL: ''
  
jobs:
- jobs: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  
  steps:
  - bash: |
      VERSION=$(git tag --sort=-version:refname | head -1)
      MAJOR=`echo $VERSION | awk -F "." '{print $1}'`
      MINOR=`echo $VERSION | awk -F "." '{print $2}'`
      PATCH=`echo $VERSION | awk -F "." '{print $3}'`
      
      if [ "$LABEL" == "MAJOR" ]
  ##increase major and don't cascade
      then
        MAJOR=$((MAJOR+1))
        MINOR="0"
        PATCH="0"
        parameters.CASCADES=NULL
      
      elif [ "$LABEL" == "MINOR" ]
  ##increase minor -> has to cascade
      then
        MAJOR="0"
        MINOR=$((MINOR+1))
        PATCH="0"
      
      else
  ##its a patch -> has to cascade
        MAJOR="0"
        MINOR="0"
        PATCH=$((PATCH+1))
      fi
      
      git tag -a "$MAJOR"."$MINOR"."$PATCH"
      echo "No longer in version $(VERSION)"
      echo "New version : $(MAJOR).$(MINOR).$(PATCH)"
      git push --tags
  ##to be continued
    displayName: Update Version tag
