parameters:
  name: 'Typescript_Job'
  buildConfiguration: 'Release'
  pool: Default
  CASCADES: ''

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}

  steps:
  - bash: |
      export VERSION=$(git tag --sort=-version:refname | head -1)
      echo $BUILD_REASON $BUILD_SOURCEVERSION $VERSION
      echo "##vso[task.setvariable variable=VERSION]$VERSION"

      echo "Cascade to:"
      for item in ${CASCADES[*]}
      do
        printf "  %s\n" $item
      done
    displayName: Set Version

  - script: |
      echo The version is $(VERSION)
    displayName: Show version

  - checkout: self
    submodules: recursive

  - task: NodeTool@0
    versionSpec: '12.0.0'

  - script: yarn
    displayName: Install dependencies
  - script: yarn build
    displayName: Build Solution

  - script: mocha test
  
  
  
  