parameters:
  buildConfiguration: 'Release'
  pool: Default
  CASCADES: ''

jobs:
- job: 'Typescript_Pipeline'
  pool: ${{ parameters.pool }}
  steps:
  - task: NodeTool@0
    displayName: 'Ensuring version'
    inputs:
      versionSpec: '>=12.0.0'
  
  - script: npm i yarn -g
    displayName: 'Installing yarn'
  
  - script: yarn
    displayName: 'Installing dependencies'
    
  - script: yarn build
    displayName: 'Building the typescript project'

  - script: yarn test:run
    displayName: 'Running tests'

- job: 'Release'
  pool: ${{ parameters.pool }}
  variables:
  - group: global-var-pipelines
  steps:
  - template: ./release.yml

- job: 'Documentation'
  pool: ${{ parameters.pool }}
  variables:
  - group: global-var-pipelines
  steps:
  - template: ../Documentation/documentation.yml