parameters:
  buildConfiguration: Release
  pool: Default
  CASCADES: ''

jobs:
- job: Build
  pool: ${{ parameters.pool }}
  variables:
  - group: global-var-pipelines
  steps:
  - template: ./build.yml
  
- job: Release
  pool: ${{ parameters.pool }}
  dependsOn: Build
  condition: succeeded()
  variables:
  - group: global-var-pipelines
  steps:
  - template: ./release.yml

#- job: Documentation
#  pool: ${{ parameters.pool }}
#  dependsOn: Build
#  variables:
#  - group: global-var-pipelines
#  steps:
#  - template: ../Documentation/documentation.yml