parameters:
  pool: Default
  pipPackageName: ''
  nugetPackageName: ''
  npmPackageName: ''

jobs:
  - job: "ContractsClone"

    steps:
    - bash: git clone --recursive https://github.com/dolittle-tools/Contracts.Build.git
      displayName: Clone Contracts Build

  - job: "Initialize"
    pool: ${{ parameters.pool }}

    steps:
    - checkout: self
      submodules: recursive

    - template: ../Versioning/set_version_variable.yml

  - job: "Python"
    pool: ${{ parameters.pool }}
    dependsOn: "Initialize"
    condition: succeeded()
    variables:
      - group: python
      - group: global-var-pipelines
      - name: NEW_VERSION
        value: $[ dependencies.Initialize.outputs['set_version.Version'] ]
      - name: IsMerge
        value: $[ dependencies.Initialize.outputs['set_version.IsMerge'] ]

    steps:
      - template: "./python.yml"
        parameters:
          packageName: ${{ parameters.pipPackageName }}
          NEW_VERSION: $(NEW_VERSION)
          IsMerge: $(IsMerge)

  - job: "CSharp"
    pool: ${{ parameters.pool }}
    dependsOn: "Initialize"
    condition: succeeded()
    variables:
      - group: global-var-pipelines
      - name: NEW_VERSION
        value: $[ dependencies.Initialize.outputs['set_version.Version'] ]
      - name: IsMerge
        value: $[ dependencies.Initialize.outputs['set_version.IsMerge'] ]

    steps:
      - template: "./csharp.yml"
        parameters:
          packageName: ${{ parameters.nugetPackageName }}
          NEW_VERSION: $(NEW_VERSION)
          IsMerge: $(IsMerge)

  - job: "TagRepository"
    dependsOn: "Initialize"
    variables:
      - group: global-var-pipelines
      - name: NEW_VERSION
        value: $[ dependencies.Initialize.outputs['set_version.Version'] ]
      - name: IsMerge
        value: $[ dependencies.Initialize.outputs['set_version.IsMerge'] ]

    steps:
      - template: ../Github/set_github_constants.yml

      - template: ../Versioning/commit_version_tag.yml
        
        parameters:
          NEW_VERSION: $(NEW_VERSION)
          REPO: $(github_constants.Repo)
          BRANCH: $(github_constants.Branch)  
          IsMerge: $(IsMerge)
